module.exports = [
  'fullstack',
  'fullstack-typescript',
  'client',
  'client-typescript',
  'node-library',
  'node-library-typescript',
  'business-manager-module',
  'business-manager-module-typescript',
  'component-library',
  'component-library-typescript',
  'universal',
  'universal-typescript',
  'server',
  'server-typescript',
];
