describe('React application', () => {
  it('should display title', async () => {
    await page.goto(app.getUrl('/'));

    expect(await page.$eval('h2', e => e.innerText)).toEqual(
      'This project was generated by yoshi!',
    );
  });
});
